### ISSUE TITLE
support Clang for OpenMP testing

### ISSUE THREAD

**Issue by jeffhammond** [ParRes/Kernels#28]
@jcownie-intel would like us to do this.

If Clang 3.8 (most recent package in the [whitelist](https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise) supports OpenMP, then this is easy.  If we have to build from source, it's not worth it.  There may be a middle ground (package install from userspace).

**Comment by jcownie-intel** [comment]
If Clang 3.8 (most recent package in the whitelist<https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise>) supports OpenMP then this is easy

I believe that OpenMP should be fine in Clang 3.8; in 3.7 you had to use –fopenmp=libomp but I think that is all fixed in 3.8.

-- Jim

James Cownie <james.h.cownie@intel.com>
SSG/DPD/TCAR (Technical Computing, Analyzers and Runtimes)
Tel: +44 117 9071438

**Comment by jeffhammond** [comment]
Can I use GOMP for the runtime library?  `libgomp` is on the whitelist (https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise#L5015) but `libomp` is not.  I would really like to not have to build the OpenMP runtime library from source...

**Comment by jcownie-intel** [comment]
libomp should be installed as part of clang, I believe.

You can’t use libgomp, it has a different ABI from that which is used by clang.
(Most of the libgomp ABI is supported by libomp, so you could use gcc compiled code with libomp, but libgomp does not support the ABI used buy clang, so the other way around does not work).

-- Jim

James Cownie <james.h.cownie@intel.com>
SSG/DPD/TCAR (Technical Computing, Analyzers and Runtimes)
Tel: +44 117 9071438

**Comment by jeffhammond** [comment]
Resolved by the series of commits ending in 8a12ce200264a17b34aa7b22d2a9b67e85f07401, i.e. PR https://github.com/ParRes/Kernels/pull/38.

**Comment by jeffhammond** [comment]
Note that this is a partial resolution, because we only test Clang-OpenMP on Mac and as part of the Homebrew package.

We will support Clang 3.8 packages in Linux eventually.
