### ISSUE TITLE
add OpenCoarrays to Travis for Fortran 2008 testing

### ISSUE THREAD

**Issue by jeffhammond** [ParRes/Kernels#72]
Currently we are only able to test `-fcoarray=single` because GCC does not ship with multi-image coarray support enabled.

**Comment by jeffhammond** [comment]
@zbeekman: it sounds like you are working on this, so I will wait for your success and then copy it.

**Comment by zbeekman** [comment]
Hey @jeffhammond 
I'm curious what you need. We have OpenCoarrays [building and running on Travis-CI](https://travis-ci.org/sourceryinstitute/opencoarrays/builds/110629309), both under [OS X](https://travis-ci.org/sourceryinstitute/opencoarrays/jobs/110629313) and [Linux](https://travis-ci.org/sourceryinstitute/opencoarrays/jobs/110629316) (containerized).

I am, however, currently in the process of refactoring our [.travis.yml](https://github.com/sourceryinstitute/opencoarrays/blob/master/.travis.yml) which currently uses only inlined shell script. My goal is to expand the build matrix a bit more, to make `.travis.yml` more concise/legible and to attempt to get gcc > 5.2 on the Linux build.

The main dependency hurdles are GCC/GFortran >= 5.1, a recent CMake and a recent MPI implementation with support for a number of MPI-3 features. For OS X this is as trivial as `brew update; brew install gcc; brew install cmake; brew install mpich`. This will install the latest stable release of each of these packages. On the containerized linux builds, we have to [add two white-listed PPAs](https://github.com/sourceryinstitute/opencoarrays/blob/master/.travis.yml#L53-L56) to easily get a suitable CMake and GCC. Unfortunately, `ubuntu-toolchain-r-test` only contains GCC/GFortran 5.2, which has decent CAF support, but there are some bugs, and features only present in 5.3. I then [build and cache MPICH](https://github.com/sourceryinstitute/opencoarrays/blob/master/.travis.yml#L117-L134) so that it doesn't need to be built more than once.

**Comment by jeffhammond** [comment]
@zbeekman Cool.  Thanks for the details.  I will check out your setup and see how to integrate it.  I assumed you were unable to test due to the GCC build bottleneck, but I misunderstood.

**Comment by zbeekman** [comment]
No problem. If you hit any show stoppers I can try to take a look. The TL;DR version is:

 - OS X: use homebrew to install a recent gcc, cmake, mpich
 - Linux (container): Use the two whitelisted PPAs to get  a sufficiently recent CMake and GFortran 5.2, then build mpich from source (and optionally cache it so your future builds don't have to do this).

**Comment by jeffhammond** [comment]
Yeah, I looked at building OpenCoarrays on my laptop, but CMake gave me pause.  My local setup is rather complicated w.r.t. MPICH (I have builds for three compiler toolchains, among other things) and I wasn't sure if it was going to detect things properly.  I guess I should try Travis, because I care less if Travis instances fail :-)

**Comment by zbeekman** [comment]
I'd be happy to look into helping you build OpenCoarrays on your laptop. Just get in touch with me over gchat. The install.sh script is targeted at old-school scientists, engineers, etc. to try to make things easy for them. If you can get a recent CMake, GCC 5.3 and MPICH or OpenMPI built against that GCC, then the direct CMake install might be the way to go for an advanced user, like you.

**Comment by jeffhammond** [comment]
@zbeekman Okay, I'll just use CMake directly, after I run `cmake .. --help` to get a list of options ;-)

**Comment by zbeekman** [comment]
I lost track of where we had been discussing GASNet, but I took a look at the Homebrew GASNet formula. It *does* install UDP and SMP conduits, but I think, in their current state, they may be broken, because of the way that Homebrew interacts with GASNet writing stub/include makefiles. I have a workaround for this, but it's not acceptable to the Homebrew  maintainers, so I am exploring alternatives.

As for OpenCoarrays, on my private branch, which I hope to merge in the next few days, I have a more comprehensive build matrix setup. It is a little bit unorthodox in that it uses Linuxbrew on the Travis-CI container builds, so that GCC 5.3 (instead of 5.2) can be used to compile and run open coarrays.

**Comment by jeffhammond** [comment]
I started working on this in https://github.com/jeffhammond/PRK/tree/travis-opencoarrays.  For now, I will only try to get the MPI-3 RMA implementation working, although I did add a GASNet install script already.

**Comment by jeffhammond** [comment]
https://github.com/ParRes/Kernels/pull/104 will resolve this when merged.

**Comment by jeffhammond** [comment]
https://github.com/ParRes/Kernels/pull/111 resolves this on Linux.  Once it is merged, I will close the issue.
