### ISSUE TITLE
merge/systematize MPI1, AMPI and FG_MPI

### ISSUE THREAD

**Issue by jeffhammond** [ParRes/Kernels#85]
The MPI-1 oriented implementations that use standard MPI, AMPI and FG-MPI are not different enough to justify separate source files.  We should figure out a way to merge them and support the minor differences with preprocessor macros, etc.

The changes encouraged in #83 might be large enough to justify a separate code, although they may be rather similar to the MPI+MPI aka MPISHM implementation.  Need to think about this more...

**Comment by rfvander** [comment]
Right now these versions are indeed almost the same. Once we allow rank migration in AMPI the code will start to differ from the standard MPI-1 form, but mostly in the form of additions (PUP routines). Zero copy within the node in FG_MPI would be another differentiator. This does indeed require careful thinking. Avoiding unnecessary divergence of multiple nominally identical versions is a good goal.

**Comment by jeffhammond** [comment]
One way to deal with this would be to factor out the input parsing, initialization and error-checking code into a separate piece of code, so that a greater fraction of what is in each PRK is specific to each model.

**Comment by rfvander** [comment]
That would be a sane structural solution. One thing I have tried to strive for is to keep the kernels self-contained as much as possible. There will often be people who try to isolate exactly the kernel of their interest—because they want to port it to their favorite runtime—and who do not want to have to extricate it from a framework. With the exception of branch and stencil (because building them invokes a script that generates code) that is still possible today. Folks put in a stub for bail_out and use their own timer. Then all they need to do is copy the one source file that represents the kernel and they can compile an run it in isolation. We need to keep this important usage mode in mind when we share sources between kernels (input parsing, initialization, verification).

**Comment by jeffhammond** [comment]
@rfvander Indeed, and I am very sensitive to that.  The PRK heap management wrappers (`prk_malloc`, `prk_free` and the SHMEM equivalents) are all implemented as `static inline` in the appropriate header file, to unsure that no new dependency is created.

As for bail_out and timers, I think we should make those `static inline` in headers as well.  It makes it easier to build since then we can just compile the source to the binary directly, rather than building object files and linking them in a second step.

As for stencil, I still need to investigate how the performance varies between C99 VLA, your `*.incl` approach and the other one.  I found that full inlining with the Intel pragma made C99 VLA perf worse, so it's possible that the Intel compiler at least doesn't need the `*.incl` solution.  However, we should be fully data-driven on this topic.

**Comment by jeffhammond** [comment]
This is below the ZBB line.
