### ISSUE TITLE
use preprocessor-friendly OpenMP syntax

### ISSUE THREAD

**Issue by jeffhammond** [ParRes/Kernels#9]
We should use C99/C++11 `_Pragma` to hoist out any inline preprocessing of OpenMP constructs.

See https://github.com/jeffhammond/nwchem-tce-triples-kernels/blob/master/src/pragma_openmp.h for how this works.

Among other things, this will allow us to use OpenMP 4 features like `omp simd` when compilers support it (as the Intel compiler does).

**Comment by jcownie-intel** [comment]
I prefer a macro style that uses `__VA_ARGS__` as well as `_Pragma`,  since that allows you to pass through the commas that may become necessary (consider wrapping `#pragma omp parallel shared(x), private(y)`).

Something more like this
```
#define stringize1(x) #x
#define stringize(x) stringize1(x)
#define PRAGMA(...) _Pragma(stringize(__VA_ARGS__))

#if (USE_PARALLEL)
# define PARALLEL(...) PRAGMA (omp parallel __VA_ARGS__)
#else
# define PARALLEL(...)
#endif
```

Using this approach you could have a single `SIMD(...)` macro (`#define SIMD(...) PRAGMA(omp simd __VA_ARGS__)`) to wrap everything simd related. 
I think you'll need something like this because the simd pragmas can be quite complex with many optional clauses and variable descriptions.

**Comment by jeffhammond** [comment]
Good suggestion.  This is standard ISO C/C++, right?

**Comment by jcownie-intel** [comment]
According to https://en.wikipedia.org/wiki/Variadic_macro : "Variable-argument macros were introduced in 1999 in the ISO/IEC 9899:1999 (C99) revision of the C language standard, and in 2011 in ISO/IEC 14882:2011 (C++11) revision of the C++ language standard.[1]"

**Comment by jeffhammond** [comment]
Excellent.  We are happy to assume C99 or C++11 in the PRK project.

**Comment by jeffhammond** [comment]
Ah, I see.  Thanks.  I'm not sure how I'm supposed to discover which repos I need to add for each package on the whitelist, but I assume there's a way and I am just ignorant of it.

**Comment by jeffhammond** [comment]
Implemented in https://github.com/ParRes/Kernels/blob/master/C1z/prk_util.h and https://github.com/ParRes/Kernels/blob/master/Cxx11/prk_util.h.
